apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: basic-cluster
  region: ap-southeast-1

vpc:
  id: vpc-8fb771e9
  subnets:
    private:
      ap-southeast-1a: { id: subnet-0943e86f }
      ap-southeast-1b: { id: subnet-80f823c8 }
      ap-southeast-1c: { id: subnet-7643252f }  
  
nodeGroups:
  - name: node-1
    instanceType: t2.micro
    desiredCapacity: 1
    volumeSize: 30
 
  - name: node-2
    instanceType: t2.micro
    desiredCapacity: 1
    volumeSize: 30
    