apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: basic-cluster
  region: ap-southeast-1

nodeGroups:
  - name: node-1
    instanceType: t2.micro
    desiredCapacity: 1
    volumeSize: 30
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: node-2
    instanceType: t2.micro
    desiredCapacity: 1
    volumeSize: 30
    ssh:
      publicKeyPath: ~/.ssh/ec2_id_rsa.pub