apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: basic-cluster
  region: ap-southeast-1
  zones : us-east-1a,us-east-1b,us-east-1d
vpc:
  id: vpc-8fb771e9
  
nodeGroups:
  - name: node-1
    instanceType: t2.micro
    desiredCapacity: 1
    volumeSize: 30
 
  - name: node-2
    instanceType: t2.micro
    desiredCapacity: 1
    volumeSize: 30
    